### PR TITLE
Update system.prop

### PR DESCRIPTION
**Pull request by percy-g2**

### CODE REVIEW

**Comment by raymanfx** [comment]
This is not the right way to do it, new props should be set via aoba.mk.
Other than that, your props are useless except for the ADB ones, but I already know of them and they are only useful for debugging purposes and should be added locally only.

**Comment by percy-g2** [comment]
Yes , As i heard cm-11 is not booting on aoba. only major changes are storage related in kitkat  and it doesn't matter if you set these here or in device make file

**Comment by raymanfx** [comment]
Well, your build.prop 'tweaks' won't help at it ;)
Not to speak of how most them are not even doing a thing anymore.

**Comment by nelikp** [comment]
as far as i know mmblock for aoba is 15
thanks for all
and another one file that i very familiar is "pre_hw_config.sh"
from here 
android_device_sony_aoba / prebuilt 
but i dont know how to change but it should be like this
to LED brighter (it's too dim before)

# LMU AS3676 Configuration for Chargemon

dev=/sys/class/leds
echo 0 > $dev/lcd-backlight/als/enable #Sensor on/off. 1 = on, reg 90h
echo 20000 > $dev/lcd-backlight/max_current
echo 7000 > $dev/red/max_current
echo 7000 > $dev/green/max_current
echo 7000 > $dev/blue/max_current

**Comment by raymanfx** [comment]
Nelikp, please STOP spamming me with pull requests. Do one properly instead if you are 100% sure about your code.
And these ALS changes don't matter at all, the device needs to be booting at first :)

**Comment by nelikp** [comment]
Sorry RaymanFx 
now i Know what is pull request 
thanks

**Pull request closed without merging**
